---
title: "Loops and Functions"
author: "Rachel Swick"
format: html
---

```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
transects <- c("Transect A", "Transect B", "Transect C")

week_matrix <- matrix(nrow = length(weekdays), ncol = length(transects))

for (i in 1:length(transects)){
  for (j in 1:length(weekdays)){
    week <- paste(weekdays[j], transects[i])
    week_matrix[j, i] <- week
  }
}
```

```{r}
force <- function(mass, accleration){
  output = mass * accleration
  return(paste("The resulting force is", output, "Newtons."))
}

force(mass = 2, accleration = 5) # testing function
```


```{r}



fish_weight <- function(fish_name, tot_length){
  if (!fish_name %in% c("Milkfish", "Great barracuda","Giant trevally")) {
    stop("This spcecies is not included. Please enter a different, common fish name")
  }
 # if (tot_length <= 0){
  #  stop("This equation does not accept negative or zero values")
 # } 
  fish_parms <- data.frame(sci_name = c("Chanos chanos", 
                                        "Sphyraena barracuda",
                                        "Caranx ignobilis"),
                         common_name = c("Milkfish", 
                                         "Great barracuda",
                                         "Giant trevally"),
                         a_est = c(0.0905, 0.0181, 0.0353),
                         b_est = c(2.52, 3.27, 3.05))
  
  fish_select <- fish_parms %>% dplyr::filter(common_name == fish_name)
  weight <- fish_select$a_est * tot_length^fish_select$b_est
  print(weight)
}

fish_weight("Milkfish", 5)

fish_lengths <- seq(from = 1, to = 100, by = 1)

milkfish_weights <- fish_weight("Milkfish", fish_lengths)


```


```{r}
wave_vec <- seq(from = 0, to = 3, by = 0.2)

wave_power <- function(wave_height, period){
  power = 0.5 * wave_height^2 * period
  return(power)
}

wave_power(wave_vec, 8)
```



































